### ISSUE TITLE
Feedback needed

### ISSUE THREAD

**Issue by narendrasinghrathore** [narendrasinghrathore/sketch-assistant-spell-check#1]
Hi @christianklotz  @jedrichards @michelegera 
I have developed a sketch assistant that let you check spelling mistakes in your sketch files and list all of them.
Also, try to give a suggestion(s).

I hope you can run the plugin and let me know what you think.
https://drive.google.com/file/d/1XtejYL8uvEK_l9XMYDHOACYqaO9i5ulz/view?usp=sharing

Waiting for your feedback.

Regards
Narendra Singh

**Note:**
**I have tested on my Windows OS machine by running a unit test ( as sketch doesn't support Windows OS).**

**Comment by christianklotz** [comment]
Great work on the spell checker! Glad to see the test driven approach worked for you on Windows 😊 Your Assistant is working nicely, as expected within Sketch as you can see below 🎉

![image](https://user-images.githubusercontent.com/69443/93435978-d8a90e80-f8d2-11ea-9e50-b70f02972fdf.png)

A few thoughts:

1. I had to replace `rmdir /s/q dist` in the `build` script in package.json with `rm -rf`, probably because you're using Windows and I'm on macOS. Maybe there's a command that works cross platform.
1. Make sure to use your Assistant name, `sketch-assistant-spell-check` or perhaps better `sketch-spellcheck-assistant`, `sketch-simple-spellchecker-assistant` or something similar across your code base. For the last two you could perhaps import the package.json using `import pkg from '../package.json` and use `pkg.name`?
    - https://github.com/narendrasinghrathore/sketch-assistant-spell-check/blob/master/package.json#L2
    - https://github.com/narendrasinghrathore/sketch-assistant-spell-check/blob/master/src/index.ts#L97
    - https://github.com/narendrasinghrathore/sketch-assistant-spell-check/blob/master/src/index.ts#L101
1. Consider changing the rule title to "Use correct spelling", i.e. make it clear what is _expected_ from the user, see https://developer.sketch.com/assistants/rules-and-reports for best practice.
1. Similar for the [rule description](https://github.com/narendrasinghrathore/sketch-assistant-spell-check/blob/master/src/index.ts#L92), maybe better _"Use correct spelling in your text layers"_ to instruct the user _what_ to do. 
1. Instead of [`textNoLoremIpsum`](https://github.com/narendrasinghrathore/sketch-assistant-spell-check/blob/master/src/index.ts#L34) use a variable name that defines more what the rule does, e.g. `correctSpelling` or `spellCheck`
1. I don't think [`@skpm/fs`](https://github.com/narendrasinghrathore/sketch-assistant-spell-check/blob/master/package.json#L50) should be a dependency. It can only be used within the [Sketch Plugin JavaScript environment](https://developer.sketch.com/plugins/javascript-environment) which dynamically exposes the Objective-C runtime and is entirely different from the [Assistants environment](https://developer.sketch.com/assistants/javascript-environments).

**Comment by jedrichards** [comment]
Nice work! 👏 😄 

Bear in mind that Assistant rules are run every time the document changes, and the code inside your text layer loop runs for every text layer in the document. So you want to do the minimal amount of work possible here, since they are hot code paths.

For example I note you're transforming your entire word list to lowercase every time you search it. If possible you want to move as much work as possible outside of your rule function, and make word lookups as fast as possible (perhaps different data structures could be explored, rather than a plain array, I'm not sure).

https://github.com/narendrasinghrathore/sketch-assistant-spell-check/blob/3b6d091a6eaf993b5930e187be7590b6516b070a/src/index.ts#L71

**Comment by narendrasinghrathore** [comment]
@christianklotz @jedrichards  Thanks for taking the time and giving valuable feedback. 
Will improve definitely.

> Stay tuned for updates ✨✨🎁🎁

**Comment by narendrasinghrathore** [comment]
@christianklotz 
- [x]  I had to replace rmdir /s/q dist in the build script in package.json with rm -rf, probably because you're using Windows and I'm on macOS. Maybe there's a command that works cross platform.
```   
"test": "jest --no-cache",
"build": "rm -rf /s/q dist && npm run build:node && npm run build:sketch",
"build-windows": "rmdir /s/q dist && npm run build:node && npm run build:sketch", // For windows
"build:node": "tsc",
"build:sketch": "webpack",
"package-tarball": "npm run build && npm pack",
"ptw":"npm run build-windows && npm pack" // For windows
```


- [x] Make sure to use your Assistant name, sketch-assistant-spell-check or perhaps better sketch-spellcheck-assistant, sketch-simple-spellchecker-assistant or something similar across your code base. For the last two you could perhaps import the package.json using import pkg from '../package.json and use pkg.name?
 https://github.com/narendrasinghrathore/sketch-assistant-spell-check/blob/master/package.json#L2 https://github.com/narendrasinghrathore/sketch-assistant-spell-check/blob/master/src/index.ts#L97 https://github.com/narendrasinghrathore/sketch-assistant-spell-check/blob/master/src/index.ts#L101

- [x] Consider changing the rule title to "Use correct spelling", i.e. make it clear what is expected from the user, see https://developer.sketch.com/assistants/rules-and-reports for best practice.
- [x] Similar for the rule description, maybe better "Use correct spelling in your text layers" to instruct the user what to do.
- [x] Instead of textNoLoremIpsum use a variable name that defines more what the rule does, e.g. correctSpelling or spellCheck
- [x] I don't think @skpm/fs should be a dependency. It can only be used within the Sketch Plugin JavaScript environment which dynamically exposes the Objective-C runtime and is entirely different from the Assistants environment.

@jedrichards 
- [x] Text transformation while looping removed and also limiting the iteration for suggestion list. Improvement of 2 sec for same test files.

Please test and let me know your valuable feedback.

[sketch-spellcheck-assistant-1.0.1.zip](https://github.com/narendrasinghrathore/sketch-assistant-spell-check/files/5280583/sketch-spellcheck-assistant-1.0.1.zip)
